language: node_js

node_js:
  - '12'
  - '11'
  - '10'

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run buildAndTest

after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls
    coveralls < ./coverage/lcov.info