language: node_js

node_js:
  - '13'
  - '12'
  - '11'
  - '10'

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run buildAndTest

after_script:
  - |
    npm install --save-dev coveralls
    coveralls < ./coverage/lcov.info

before_deploy:
  - cd dist

deploy:
  provider: npm
  email: $NPM_TESTE #$NPM_EMAIL
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master
#    tags: true
    
#
#- npm run setnpmtoken
#        - npm run publish