language: node_js

node_js:
  - '13'
  - '12'
  - '11'
  - '10'

cache:
  npm: true
  directories:
    - node_modules

#script:
#  - npm run buildAndTest

jobs:
  include:
    - stage: compile
      script:
        - npm run build
    - stage: test
      script:
        - npm run test
    - stage: coverage
      script:
        - npm install --save-dev coveralls
        - coveralls < ./coverage/lcov.info
    - stage: deploy
      script:
        - npm run setnpmtoken
        - npm run publish


#after_script:
#  - |
#    # Upload coverage to coveralls
#    npm install --save-dev coveralls
#    coveralls < ./coverage/lcov.info

stages:
  - compile
  - test
  - coverage
  - name: deploy
    if: branch = master