language: node_js

node_js:
  - '13'
  - '12'
  - '11'
  - '10'

cache:
  npm: true
  directories:
    - node_modules

script:
  #- npm run buildAndTest
  - echo "****"
  - echo "$NPM_TESTE"
  - echo "$NPM_EMAIL"
  - echo "****"

#after_script:
#  - |
#    npm install --save-dev coveralls
#    coveralls < ./coverage/lcov.info

#before_deploy:
#  - cd dist

#deploy:
#  provider: script
#  script: bash npm 
#  on:
#    branch: master
#    tags: true

#deploy:
  #provider: npm
  #email: "$NPM_EMAIL"
  #api_key:
  #  secure: "$NPM_TOKEN"
  #on:
  #  branch: master
#    tags: true
#
#- npm run setnpmtoken
#        - npm run publish