name: Publish

on:
  push:
    tags:
       - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: npm install, coverage, and publish
      run: |
        npm install
        npm install coveralls
        npm run build
        npm run test:coverage
        coveralls < ./coverage/lcov.info
        npm run setnpmtokenAndPublish