name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install coveralls
    - run: npm run build
    - run: npm run test:coverage
    - run: coveralls < ./coverage/lcov.info
    - run: npm run setnpmtokenAndPublish
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}